name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.111.3
        HUGO_EXTENDED: true
        GO_VERSION: 1.17
        TARGET_REPO: bfonta/bfonta.github.io
        TOKEN: ${{ secrets.PAGES_TOKEN }}
        CNAME: www.brunoalves.com
